# This docker-compose is for development only
# For production, the docker-compose.prod.yml will be defined in portainer.io

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: banking-v7-api
    restart: unless-stopped
    environment:
      DOMAIN: localhost
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@banking-v7-postgres:5432/postgres
      API_PORT: 80
    depends_on:
      - database
    volumes:
      - type: bind
        source: "./api"
        target: "/app"
    command: yarn run dev
    ports:
      - 3000:80
    networks:
      - default

  database:
    image: postgres:16.1-bullseye
    container_name: banking-v7-postgres
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    networks:
      - default

  # Postgres web-based database tool, development only
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: banking-v7-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@navarrotech.net
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - 5051:80
    networks:
      - default
    depends_on:
      - database
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
 
networks:
  default:
